### ISSUE TITLE
German Umlaute

### ISSUE THREAD

**Issue by mprofitl** [twiro/reflecteduploadfield#11]
The extension removes letters such as ä, ö, ü. Names get wrong. It would be nice if the extension could convert ä to ae, ö to ue and ü to ue.

**Comment by twiro** [comment]
I couldn't replicate this behaviour with the latest version of this extension – all Umlauts are properly transfomed to 'ae', 'oe' or 'ue'… do you still have troubles with this? Otherwise I'm going to close this bug after leaving it open for 3 years ;)

By the way: I think it's the Symphony core that makes these transformations – not the extension itself…

**Comment by mprofitl** [comment]
It is indeed solved. Just checked in one of my projects. Until know the word `Überbauung` turned into `u-berbauung`, now after saving the entry again it is `ueberbauung`.
