### ISSUE TITLE
File path error when used with Symphony 2.3.3

### ISSUE THREAD

**Issue by mprofitl** [twiro/reflecteduploadfield#6]
This extension still works with Symphony 2.3.3 but an error is displayed all the time: "The file uploaded is no longer available. Please check that it exists, and is readable."
also see http://www.getsymphony.com/discuss/thread/80974/#position-13 

This seems to be as Symphony no differently handles file paths.
also see http://www.getsymphony.com/discuss/thread/80974/#position-14

It would be wonderful if you could have a look into this and update the extension. Thanks a lot!

**Comment by twiro** [comment]
:wave: hey Moritz :) Hast den Fehler zwar schon längst selbst behoben, aber...

.. officially fixed in [version 1.2](https://github.com/twiro/reflecteduploadfield/tree/1.2)

Hab die Extension "adoptiert" und werd die kommenden Wochen/Monate mal versuchen den Code auf Vordermann zu bringen... evtl. lässt sich dabei ja auch dein [Germanumlatuproblem](https://github.com/twiro/reflecteduploadfield/issues/11) beheben.
